# Generated by Django 3.1.1 on 2020-09-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='dis_likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
